### ISSUE TITLE
Unofficial mappings required

### ISSUE THREAD

**Issue by ThexXTURBOXx** [makamys/MCLib#3]
I want to use MCLib in a mod of mine (for 1.7.10).
Shading it into my mod was not a big deal - so I wanted to test whether the update checker worked.
I just set my version lower than what the update json suggests.
MCLib finds the update successfully and shows it on the main menu.
However, upon hovering over the "+1" button, the game crashes with the following stack trace:

```
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchFieldError: fontRenderer
	at ckathode.weaponmod.repackage.makamys.mclib.updatecheck.Util.drawSimpleTooltip(Util.java:30) ~[Util.class:1.20.0]
	at ckathode.weaponmod.repackage.makamys.mclib.updatecheck.gui.GuiButtonGeneric.func_146112_a(GuiButtonGeneric.java:45) ~[GuiButtonGeneric.class:1.20.0]
	at ckathode.weaponmod.repackage.makamys.mclib.updatecheck.gui.GuiButtonUpdates.func_146112_a(GuiButtonUpdates.java:43) ~[GuiButtonUpdates.class:1.20.0]
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:52) ~[bdw.class:?]
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:522) ~[bee.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) ~[blt.class:?]
	... 12 more
```

The core of the issue is clear: `fontRenderer` is not remapped properly. So, I asked myself: why?
Turns out that every official MCP mappings version (from stable 8-1.7.10 to stable 12-1.7.10 and even to the last snapshot 20140925-1.7.10) expects a field `fontRendererObj` instead.
After looking at the GNTH modding template (which I am *not* using), I found that they use the following remote mappings: https://github.com/MinecraftForge/FML/tree/1.7.10/conf
Indeed, these contain the `fontRenderer` field and hence lack `fontRendererObj`.
However, as far as I can tell, these were never meant to be official mappings. So, I am unsure as to why it is expected to use these instead of the official MCP exports?

It might also very well be that there are even more differences (and hence more possible crashes)!
Do you have any suggestions? I don't really like to use unofficial mappings in my mod and also I don't really want to migrate to another modding template again.
Is there even something that makes it possible to use MCLib in my scenario?

**Comment by ThexXTURBOXx** [comment]
I was able to work around this by reading the mappings from `conf/*.csv` within the Forge userdev jar - quite hacky, but works for now.
Just for anyone else having this exact issue :)
